export const publishers = [
  "4SE..",
  "Abalon",
  "Admiral Books",
  "Agencija EHO",
  "Agencija SIGMA KONSULT PLUS",
  "AGM knjiga",
  "Agora",
  "Akademska knjiga",
  "Albatros plus",
  "Aleja izdavastvo",
  "Ammonite",
  "Antikvar",
  "Arete",
  "Arhipelag",
  "Arkzin",
  "Art press",
  "autorsko izdanje",
  "Autorsko izdanje - Dusan Prelevic",
  "autorsko izdanje - Kelvin Medrano",
  "autorsko izdanje - Livija Kulic",
  "Autorsko izdanje - Nemanja Antic",
  "Autorsko izdanje - Predrag Simic",
  "autorsko izdanje - Tamara Kostic",
  "Autorsko izdanje (A)",
  "autorsko izdanje Boris Durovic",
  "Autorsko izdanje Dusan Kosutic",
  "autorsko izdanje Gordana Saric",
  "autorsko izdanje Petar Janjatovic / Makart",
  "autorsko izdanje prof. dr Dusan Vesovic",
  "autorsko izdanje Rajko Martinovic",
  "Ave Serbia",
  "Ave Serbia; Vukotic Media",
  "Balbelo",
  "Balkanski centar za Bliski istok",
  "BAYA BANGUE NAMKOSSE - autorsko izdanje",
  "BELI PUT",
  "BEOBOOK",
  "Beoknjiga",
  "Besani",
  "Besna kobila",
  "Best Mind Solutions d.o.o.",
  "Biblioner",
  "Biblioteka 20. vek",
  "Biblioteka XX vek",
  "Blum izdavastvo",
  "BOOKA",
  "Boris Vukusic PR VUKU",
  "Bukefal E.O.N.",
  "Bulevar books",
  "Caligraph d.o.o.",
  "Carobna knjiga",
  "Catena Mundi",
  "Centar za istrazivanje popularne muzike Beograd",
  "Centar za promociju nauke",
  "CENTAR ZA RELIGIJSKE NAUKE KOM",
  "CET",
  "Chibi d.o.o.",
  "Chilly's",
  "Cigoja stampa",
  "CIRSD",
  "CLIO",
  "CNP&P",
  "Codex Udruzenje",
  "CREATIVE PRESS d.o.o.",
  "Dallas records",
  "Dan Graf",
  "Darkwood",
  "Darma books",
  "Data status",
  "Dedic",
  "Dereta",
  "Didakta",
  "DIGITAL D.O.O, Beograd",
  "Dizgram",
  "Dokaz",
  "Dorotej",
  "Dosije",
  "Draslar",
  "Drustvo ljubitelja popularne kulture",
  "Edicija Najbolja",
  "Ekonomija uspeha",
  "ENCO BOOK",
  "Entropija",
  "EVOLUTA",
  "Fabrika knjiga",
  "Fakultet Tehnickih Nauka",
  "FDU",
  "Fedon",
  "Filmski centar Srbije",
  "Fineks d.o.o.",
  "Finesa",
  "FMK - Fakultet za medije i komunikacije",
  "FPN (Fakultet politickih nauka)",
  "Frost media",
  "Futura publikacije",
  "Galaksijanis",
  "Ganesa klub",
  "Geopoetika",
  "Glama games",
  "Globosino",
  "GNB Zarko Zrenjanin",
  "Gnosis Lux",
  "Golconda",
  "Gold Ochrid",
  "Gradska biblioteka Karlo Bijelicki",
  "Gradjevinska knjiga",
  "Gramatik",
  "GRIF",
  "HAR press",
  "Harmonija",
  "HELIKS",
  "HERA EDU",
  "Hipatia",
  "Hoplit",
  "IK Prometej",
  "iLearn",
  "IMGS DOO BEOGRAD",
  "Imperativ",
  "Imprimatur",
  "IND Media Publishing",
  "Infinity lighthouse",
  "Informatika",
  "INK",
  "Inkomo",
  "Institut za savremenu istoriju",
  "Interklima-grafika",
  "IP Panonija-Ruma",
  "IPC",
  "ITV Centar plus",
  "Izdavacka knjizarnica Zorana Stojanovica",
  "Izdavacka kuca Vaskrsenje",
  "Izdavastvo Jeti",
  "Jagy",
  "Jasen",
  "Jesenski i Turk",
  "JRJ",
  "JSP",
  "Kalipso knjiga",
  "Kapija books",
  "KAREJA",
  "Karioke",
  "KARPOS",
  "KIND BAG",
  "Kljuc izdavastvo",
  "KNJIGE OBRADOVIC",
  "Knjizara Roman",
  "Knjizevna radionica Rasic",
  "Komiko",
  "Komshe",
  "Kontrast izdavastvo",
  "Kornet",
  "Kosmos",
  "KOZIKAS IZDAVASTVO",
  "KP Advertajzing",
  "Kreativna radionica Balkan",
  "KREATIVNI CENTAR",
  "Kuca Cuvarkuca",
  "Laguna",
  "Libretto",
  "Lingea",
  "Logopraktika",
  "LOM",
  "Lom/Knjizevna radionica Rasic",
  "LUKA BOOKS",
  "Lumo",
  "Magnus",
  "MAKART",
  "Makart, Admiral Books",
  "Makondo",
  "Mali vrt",
  "Manastir Tvrdos",
  "Marija Ajkovic pr LOVERS.RS",
  "Mascom/Booking",
  "Mate d.o.o",
  "Maverik",
  "MCB Edukacija",
  "McMillan",
  "Medjunarodno udruzenje \"Stil\"",
  "Meraklis",
  "Metaphysica",
  "MIBA BOOKS",
  "Miba Books:Narodna knjiga - Podgorica",
  "Mikro knjiga",
  "MILAN ZARIC PREDUZETNIK FITNES TRENER",
  "Milica Kljajic PR Savrseno iznenadjenje",
  "Mirdin",
  "Miroslav",
  "Mladinska knjiga",
  "Modus Vivendi",
  "MOSTART",
  "Multimedia international",
  "Muzej Vojvodine",
  "Muzicka knjiga",
  "My book",
  "Naklada Mate",
  "Narator",
  "Naucna KMD",
  "Nebula",
  "Networking",
  "NNK International",
  "Nova scena",
  "Novi liber",
  "Odiseja",
  "ODYSSEUS",
  "ORFELIN",
  "Organska basta - centar za promociju i edukaciju",
  "Orion art",
  "Otvorena knjiga",
  "Ouroboros DOO",
  "Paladin",
  "Partenon",
  "Partizanska knjiga",
  "PERISKOP",
  "Pinetrie",
  "Plato",
  "Plavi krug",
  "Poeta",
  "PortaLibris",
  "PPM Enklava",
  "Propolis Books",
  "Prosveta",
  "Psiholoski centar ProAktiva",
  "Psihopolis",
  "Publik Praktikum",
  "Radni sto",
  "Red box",
  "Reemina Limited",
  "Research Paradigmas Applied llc",
  "Revolucya",
  "RTS",
  "Saga books",
  "Sakura Publishing",
  "Senzal trade",
  "SEZAM BOOK",
  "Skripta internacional",
  "SLUZBENI GLASNIK",
  "Sluzbeni glasnik:Filmski centar Srbije",
  "Sluzbeni glasnik/Makart",
  "Smeker-devojka",
  "Solaris",
  "Solvion",
  "Soulfood",
  "Spin Press",
  "Srednja zemlja",
  "Sregitoss d.o.o.",
  "SRMA Consulting",
  "Srpska knjizevna zadruga",
  "Stampar Makarije",
  "Strik",
  "Stylos art",
  "Sumatra izdavastvo",
  "Suncani breg",
  "Svet knjige",
  "Tanesi",
  "Taschen",
  "Treci trg",
  "UCON Acrobatics",
  "Udrzenje \"Autostoperski vodic kroz fantastiku\"",
  "Udrzenje \"Mark IX''",
  "UDRUZENJE IZDAVACA VOJVODINE",
  "UDRUZENJE KNJIZEVNIKA SRBIJE",
  "Udrzenje pisaca Poeta",
  "Udrzenje Poetum",
  "Udrzenje roditelja \"Matica\"",
  "UG Kljuc",
  "Ukronija",
  "Ultimatum",
  "Umetnicko drustvo Gradac",
  "URBAN READS",
  "Uz vetar",
  "VAGANAR",
  "VBZ",
  "Veb Net Plus",
  "Vecernje novosti",
  "VEGANLUK",
  "Verba",
  "Veseli cetvrtak",
  "Vina Productions",
  "Viva Trade",
  "Vladimir Velickovic",
  "Vukotic media",
  "VULKAN IZDAVASTVO",
  "Walter Media",
  "WIZART",
  "Zaduzbina Andrejevic",
  "Zaduzbina Dositej Obradovic",
  "Zaduzbina Svetog manastira Hilandara",
  "Zaduzbina Vladete Jerotica",
  "Zavod za kulturu Vojvodine",
  "Zebra publishing",
  "Zenit books",
  "ZENIT-inzenjering",
  "Zepter Book World",
  "Zlatno runo" 
];