export const publishersLatin = [
  "4SE..",
  "Abalon",
  "Admiral Books",
  "Agencija EHO",
  "Agencija SIGMA KONSULT PLUS",
  "AGM knjiga",
  "Agora",
  "Akademska knjiga",
  "Albatros plus",
  "Aleja izdavaštvo",
  "Ammonite",
  "Antikvar",
  "Arete",
  "Arhipelag",
  "Arkzin",
  "Art press",
  "autorsko izdanje",
  "Autorsko izdanje - Dušan Prelević",
  "autorsko izdanje - Kelvin Medrano",
  "autorsko izdanje - Livija Kulić",
  "Autorsko izdanje - Nemanja Antić",
  "Autorsko izdanje - Predrag Simić",
  "autorsko izdanje - Tamara Kostić",
  "Autorsko izdanje (A)",
  "autorsko izdanje Boris Đurović",
  "Autorsko izdanje Dušan Košutić",
  "autorsko izdanje Gordana Sarić",
  "autorsko izdanje Petar Janjatović / Makart",
  "autorsko izdanje prof. dr Dušan Vešović",
  "autorsko izdanje Rajko Martinović",
  "Ave Serbia",
  "Ave Serbia; Vukotić Media",
  "Balbelo",
  "Balkanski centar za Bliski istok",
  "BAYA BANGUE NAMKOSSE - autorsko izdanje",
  "BELI PUT",
  "BEOBOOK",
  "Beoknjiga",
  "Besani",
  "Besna kobila",
  "Best Mind Solutions d.o.o.",
  "Biblioner",
  "Biblioteka 20. vek",
  "Biblioteka XX vek",
  "Blum izdavaštvo",
  "BOOKA",
  "Boris Vukušić PR VUKU",
  "Bukefal E.O.N.",
  "Bulevar books",
  "Caligraph d.o.o.",
  "Čarobna knjiga",
  "Catena Mundi",
  "Centar za istraživanje popularne muzike Beograd",
  "Centar za promociju nauke",
  "CENTAR ZA RELIGIJSKE NAUKE KOM",
  "CET",
  "Chibi d.o.o.",
  "Chilly's",
  "Čigoja štampa",
  "CIRSD",
  "CLIO",
  "CNP&P",
  "Codex Udruženje",
  "CREATIVE PRESS d.o.o.",
  "Dallas records",
  "Dan Graf",
  "Darkwood",
  "Darma books",
  "Data status",
  "Dedić",
  "Dereta",
  "Didakta",
  "DIGITAL D.O.O, Beograd",
  "Dizgram",
  "Dokaz",
  "Dorotej",
  "Dosije",
  "Draslar",
  "Društvo ljubitelja popularne kulture",
  "Edicija Najbolja",
  "Ekonomija uspeha",
  "ENCO BOOK",
  "Entropija",
  "EVOLUTA",
  "Fabrika knjiga",
  "Fakultet Tehničkih Nauka",
  "FDU",
  "Fedon",
  "Filmski centar Srbije",
  "Fineks d.o.o.",
  "Finesa",
  "FMK - Fakultet za medije i komunikacije",
  "FPN (Fakultet političkih nauka)",
  "Frost media",
  "Futura publikacije",
  "Galaksijanis",
  "Ganeša klub",
  "Geopoetika",
  "Glama games",
  "Globosino",
  "GNB Žarko Zrenjanin",
  "Gnosis Lux",
  "Golconda",
  "Gold Ochrid",
  "Gradska biblioteka Karlo Bijelicki",
  "Građevinska knjiga",
  "Gramatik",
  "GRIF",
  "HAR press",
  "Harmonija",
  "HELIKS",
  "HERA EDU",
  "Hipatia",
  "Hoplit",
  "IK Prometej",
  "iLearn",
  "IMGS DOO BEOGRAD",
  "Imperativ",
  "Imprimatur",
  "IND Media Publishing",
  "Infinity lighthouse",
  "Informatika",
  "INK",
  "Inkomo",
  "Institut za savremenu istoriju",
  "Interklima-grafika",
  "IP Panonija-Ruma",
  "IPC",
  "ITV Centar plus",
  "Izdavačka knjižarnica Zorana Stojanovića",
  "Izdavačka kuća Vaskrsenje",
  "Izdavaštvo Jeti",
  "Jagy",
  "Jasen",
  "Jesenski i Turk",
  "JRJ",
  "JSP",
  "Kalipso knjiga",
  "Kapija books",
  "KAREJA",
  "Karioke",
  "KARPOS",
  "KIND BAG",
  "Ključ izdavaštvo",
  "KNJIGE OBRADOVIĆ",
  "Knjizara Roman",
  "Književna radionica Rašić",
  "Komiko",
  "Komshe",
  "Kontrast izdavaštvo",
  "Kornet",
  "Kosmos",
  "KOZIKAS IZDAVAŠTVO",
  "KP Advertajzing",
  "Kreativna radionica Balkan",
  "KREATIVNI CENTAR",
  "Kuća Čuvarkuća",
  "Laguna",
  "Libretto",
  "Lingea",
  "Logopraktika",
  "LOM",
  "Lom/Književna radionica Rašić",
  "LUKA BOOKS",
  "Lumo",
  "Magnus",
  "MAKART",
  "Makart, Admiral Books",
  "Makondo",
  "Mali vrt",
  "Manastir Tvrdoš",
  "Marija Ajković pr LOVERS.RS",
  "Mascom/Booking",
  "Mate d.o.o",
  "Maverik",
  "MCB Edukacija",
  "McMillan",
  "Međunarodno udruženje „Stil“",
  "Meraklis",
  "Metaphysica",
  "MIBA BOOKS",
  "Miba Books:Narodna knjiga - Podgorica",
  "Mikro knjiga",
  "MILAN ZARIĆ PREDUZETNIK FITNES TRENER",
  "Milica Kljajić PR Savršeno iznenađenje",
  "Mirdin",
  "Miroslav",
  "Mladinska knjiga",
  "Modus Vivendi",
  "MOSTART",
  "Multimedia international",
  "Muzej Vojvodine",
  "Muzička knjiga",
  "My book",
  "Naklada Mate",
  "Narator",
  "Naučna KMD",
  "Nebula",
  "Networking",
  "NNK International",
  "Nova scena",
  "Novi liber",
  "Odiseja",
  "ODYSSEUS",
  "ORFELIN",
  "Organska bašta - centar za promociju i edukaciju",
  "Orion art",
  "Otvorena knjiga",
  "Ouroboros DOO",
  "Paladin",
  "Partenon",
  "Partizanska knjiga",
  "PERISKOP",
  "Pinetrie",
  "Plato",
  "Plavi krug",
  "Poeta",
  "PortaLibris",
  "PPM Enklava",
  "Propolis Books",
  "Prosveta",
  "Psiholoski centar ProAktiva",
  "Psihopolis",
  "Publik Praktikum",
  "Radni sto",
  "Red box",
  "Reemina Limited",
  "Research Paradigmas Applied llc",
  "Revolucya",
  "RTS",
  "Saga books",
  "Sakura Publishing",
  "Senzal trade",
  "SEZAM BOOK",
  "Skripta internacional",
  "SLUŽBENI GLASNIK",
  "Službeni glasnik:Filmski centar Srbije",
  "Službeni glasnik/Makart",
  "Šmeker-devojka",
  "Solaris",
  "Solvion",
  "Soulfood",
  "Spin Press",
  "Srednja zemlja",
  "Sregitoss d.o.o.",
  "SRMA Consulting",
  "Srpska književna zadruga",
  "Štampar Makarije",
  "Štrik",
  "Stylos art",
  "Sumatra izdavaštvo",
  "Sunčani breg",
  "Svet knjige",
  "Tanesi",
  "Taschen",
  "Treći trg",
  "UCON Acrobatics",
  "Udruženje „Autostoperski vodič kroz fantastiku“",
  "Udruženje \"Mark IX''",
  "UDRUŽENJE IZDAVAČA VOJVODINE",
  "UDRUŽENJE KNJIŽEVNIKA SRBIJE",
  "Udruženje pisaca Poeta",
  "Udruženje Poetum",
  "Udruženje roditelja „Matica“",
  "UG Ključ",
  "Ukronija",
  "Ultimatum",
  "Umetničko društvo Gradac",
  "URBAN READS",
  "Uz vetar",
  "VAGANAR",
  "VBZ",
  "Veb Net Plus",
  "Večernje novosti",
  "VEGANLUK",
  "Verba",
  "Veseli četvrtak",
  "Vina Productions",
  "Viva Trade",
  "Vladimir Veličković",
  "Vukotić media",
  "VULKAN IZDAVAŠTVO",
  "Walter Media",
  "WIZART",
  "Zadužbina Andrejević",
  "Zadužbina Dositej Obradović",
  "Zadužbina Svetog manastira Hilandara",
  "Zadužbina Vladete Jerotića",
  "Zavod za kulturu Vojvodine",
  "Zebra publishing",
  "Zenit books",
  "ZENIT-inženjering",
  "Zepter Book World",
  "Zlatno runo"
];